# Generated by Django 4.2.4 on 2023-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
