# Generated by Django 4.2.4 on 2023-08-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_orderitem_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_number',
        ),
    ]
